# Environment Specification for Deep CFR Architecture Study
# Python 3.9.6 on macOS

# Core Dependencies
torch==2.3.1
numpy==2.0.2
pandas==2.3.3
scipy==1.13.1
matplotlib==3.9.4
seaborn==0.13.2
scikit-learn==1.5.2

# Game Engine
pyspiel==1.6.3

# Utilities
tqdm==4.66.5
tyro==0.8.12
tables==3.10.1

# Environment Details
# Python: 3.9.6
# Platform: macOS (Darwin 24.6.0)
# OpenSpiel: 1.6.3
# PyTorch: 2.3.1

# Game Configuration
# - Kuhn Poker: pyspiel.load_game("kuhn_poker")
# - Leduc Hold'em: pyspiel.load_game("leduc_holdem")
# - Evaluation: External Sampling fixed
# - Seeds: {0, 1, ..., 19} per method
# - Iterations: 400 for both games
# - Evaluation cadence: every 20 iterations