experiment:
  num_runs: 20
  iterations: 200
  checkpoint_interval: 50
  evaluation_interval: 50
  update_threshold: 10
  batch_size: 64
  device: cpu
  random_seed: 20251004

tagents:
  include:
    - baseline
    - lstm_optimized
    - lstm_no_history
    - lstm_no_embedding
