experiment:
  num_runs: 5
  iterations: 200
  checkpoint_interval: 50
  evaluation_interval: 50
  update_threshold: 25
  batch_size: 64
  device: cpu
  random_seed: 20251004

agents:
  include:
    - baseline
    - lstm_optimized
    - lstm_no_history
    - lstm_no_embedding
