experiment:
  num_runs: 3
  iterations: 200
  checkpoint_interval: 50
  evaluation_interval: 50
  update_threshold: 25
  batch_size: 64
  device: cpu
  plot_title: "Leduc Hold'em: DCFR Noise Robustness"
  plot_output_filename: noise_ablation_exploitability.png

agents:
  include:
    - baseline
    - baseline_noise_001
    - baseline_noise_005
    - baseline_noise_010

  baseline:
    init_params:
      regret_noise_std: 0.0

  baseline_noise_001:
    name: "Baseline (σ=0.01)"
    agent_class: qagent.agents.dcfr_leduc.DCFRTrainer
    init_params:
      regret_noise_std: 0.01

  baseline_noise_005:
    name: "Baseline (σ=0.05)"
    agent_class: qagent.agents.dcfr_leduc.DCFRTrainer
    init_params:
      regret_noise_std: 0.05

  baseline_noise_010:
    name: "Baseline (σ=0.10)"
    agent_class: qagent.agents.dcfr_leduc.DCFRTrainer
    init_params:
      regret_noise_std: 0.10