experiment:
  num_runs: 5
  iterations: 200
  checkpoint_interval: 50
  evaluation_interval: 50
  update_threshold: 25
  batch_size: 64
  device: cpu
  plot_title: "Leduc Hold'em: DCFR Architecture Comparison"
  plot_output_filename: architecture_ablation_exploitability.png

agents:
  include:
    - baseline
    - lstm_optimized
    - gru
    - transformer

  lstm_optimized:
    init_params:
      embedding_dim: 64
      lstm_hidden_size: 128
      num_lstm_layers: 2
      learning_rate: 0.0005

  gru:
    init_params:
      embedding_dim: 64
      gru_hidden_size: 128
      num_gru_layers: 2
      learning_rate: 0.0005

  transformer:
    init_params:
      embedding_dim: 128
      num_heads: 8
      num_encoder_layers: 2
      learning_rate: 0.0003
